export const APP_LOADING = 'APP_LOADING';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SECTION_SUCCESS = 'LOAD_SECTION_SUCCESS';
export const LOAD_SECTION_FAIL = 'LOAD_SECTION_FAIL';

export const LOAD_WORK_SUCCESS = 'LOAD_WORK_SUCCESS';
export const LOAD_WORK_FAIL = 'LOAD_WORK_FAIL';

export const LOAD_PLAY_SUCCESS = 'LOAD_PLAY_SUCCESS';
export const LOAD_PLAY_FAIL = 'LOAD_PLAY_FAIL';

export const LOAD_GALLERY_SUCCESS = 'LOAD_GALLERY_SUCCESS';
export const LOAD_GALLERY_FAIL = 'LOAD_GALLERY_FAIL';

export const CHANGE_THEME_SUCCESS = 'CHANGE_THEME_SUCCESS';
export const CHANGE_THEME_ERROR = 'CHANGE_THEME_ERROR';
